[package]
name = "pymeta"
version = "0.0.0"
authors = ["shBLOCK <shblock3@gmail.com>"]
description = "Metaprogramming Rust in Python!"
#keywords = []
#categories = []
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
proc-macro-error2 = { version = "2.0.1", default-features = false }
quote = "1.0.44"
#syn = "2.0.114"
rustpython-vm = { git = "https://github.com/RustPython/RustPython.git", tag = "2025-11-10-main-55" }
#pyo3 = { version = "0.27.2" }