[package]
name = "pymeta"
version = "0.0.0"
authors = ["shBLOCK <shblock3@gmail.com>"]
description = "Metaprogramming Rust in Python!"
#keywords = []
#categories = []
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.106" }
proc-macro-error2 = { version = "2.0.1", default-features = false }
quote = "1.0.44"

#rustpython-vm = { git = "https://github.com/RustPython/RustPython.git", tag = "2025-11-10-main-55" }
pyo3 = { version = "0.28.0" }

rustc-literal-escaper = "0.0.7"
either = "1.15.0"
unicode-ident = "1.0.23"

log = { version = "0.4.29", optional = true }
env_logger = { version = "0.11.8", optional = true }

[features]
debug_log = [
    "dep:log",
    "dep:env_logger"
]
nightly_proc_macro_span = ["proc-macro2/span-locations"]