name: mdBook
on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Install mdBook
        run: |
          tag="v0.5.2"
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir -p $HOME/.local/bin
          curl -sSL $url | tar -xz --strip-components=1 -C $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build
        run: |
          cd docs
          python make.py build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: "book"
      - uses: actions/deploy-pages@v4
